config/routes.rb
Rails.application.routes.draw do
  resources :tabs

end

app/models/tab.rb
class Tab < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tabs_controller.rb
class TabsController < ApplicationController
  before_action :set_tab, only: [:show, :edit, :update, :destroy]

  # GET /tabs
  # GET /tabs.json
  def index
    @tabs = Tab.all
  end

  # GET /tabs/1
  # GET /tabs/1.json
  def show
    @tabs = Tab.all
  end

  # GET /tabs/new
  def new
    @tab = Tab.new
  end

  # GET /tabs/1/edit
  def edit
  end

  # POST /tabs
  # POST /tabs.json
  def create
    @tab = Tab.new(tab_params)

    respond_to do |format|
      if @tab.save
        format.html { redirect_to @tab, notice: 'Tab was successfully created.' }
        format.json { render :show, status: :created, location: @tab }
      else
        format.html { render :new }
        format.json { render json: @tab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tabs/1
  # PATCH/PUT /tabs/1.json
  def update
    respond_to do |format|
      if @tab.update(tab_params)
        format.html { redirect_to @tab, notice: 'Tab was successfully updated.' }
        format.json { render :show, status: :ok, location: @tab }
      else
        format.html { render :edit }
        format.json { render json: @tab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tabs/1
  # DELETE /tabs/1.json
  def destroy
    @tab.destroy
    respond_to do |format|
      format.html { redirect_to tabs_url, notice: 'Tab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tab
      @tab = Tab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tab_params
      params.require(:tab).permit(:artist, :title, :tab_content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<div class="navbar-header">
			<%= link_to "Tab Library", '#', class: "navbar-brand" %>
		</div>
			<ul class="nav navbar-nav">
				<li><%= link_to "Home", '/home' %></li>
				<li><%= link_to "Library", tabs_path %></li>
				<li><%= link_to "Sign in", '/signin' %></li>
			</ul>
			<div class="container">
				<%= link_to 'Play', '#', class: "btn btn-default btn-sm navbar-btn playButton" %>
				<%= link_to 'Pause', '#', class: "btn btn-default btn-sm navbar-btn pauseButton" %>
			</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TabLibrary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	
	<div class="container"><%= yield %></div>

</body>
</html>

app/views/tabs/_form.html.erb
<%= form_for(@tab) do |f| %>
  <% if @tab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tab.errors.count, "error") %> prohibited this tab from being saved:</h2>

      <ul>
      <% @tab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tab_content %><br>
    <%= f.text_area :tab_content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tabs/edit.html.erb
<h1>Editing Tab</h1>

<%= render 'form' %>

<%= link_to 'Show', @tab %> |
<%= link_to 'Back', tabs_path %>

app/views/tabs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tabs</h1>
<div class="container">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Artist</th>
				<th>Title</th>
				<th>Tab content</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @tabs.each do |tab| %>
				<tr>
					<td><%= tab.artist %></td>
					<td width="70%"><%= link_to tab.title, tab %></td>
					<td><%= link_to 'Edit', edit_tab_path(tab) %></td>
					<td><%= link_to 'Delete', tab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<br>

<%= link_to 'New Tab', new_tab_path %>

app/views/tabs/new.html.erb
<h1>New Tab</h1>

<%= render 'form' %>

<%= link_to 'Back', tabs_path %>

app/views/tabs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">Tab Library</div>
			<div class="panel panel-body">
				<ul class="list-unstyled">
					<% @tabs.each do |tab| %>
						<li><%= link_to tab.artist + " - " + tab.title, tab %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<%= @tab.artist %>
				<%= @tab.title %>
				<%= link_to 'Edit', edit_tab_path(@tab), class: "btn btn-default btn-sm" %>
				<%= link_to 'Back', tabs_path %>
				<%= link_to 'Play', '#', id: "playButton", class: "btn btn-default btn-sm" %>
			</div>
			<div class="panel-body">
				<p id="tabContent" class="tab">	
					<%= @tab.tab_content.gsub(/\n/, '<br/>').html_safe %>
				</p>
			</div>
		</div>
	</div>
</div>